apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shorten
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shorten
                port:
                  number: {{ .Values.service.port }}
